spring:
  application:
    name: vetapp

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:vetapp}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # SMTP config (para desarrollo local si lo necesitas)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:stabares_26@cue.edu.co}
    password: ${MAIL_PASSWORD:}

server:
  port: ${PORT:8080}
  error:
    include-message: always

# Configuraci√≥n personalizada
app:
  mail:
    from: ${MAIL_FROM:stabares_26@cue.edu.co}
    enabled: ${MAIL_ENABLED:true}
  resend:
    api-key: ${RESEND_API_KEY:re_ipvLA8Qi_CYb33L8k6RPR38ALX43wmFcG}
    from: "VetApp <onboarding@resend.dev>"

logging:
  level:
    root: INFO
    com.veterinaria: DEBUG